[project]
name = "derby"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.4"
dependencies = ["coinbase-agentkit", "mss>=10.0.0", "textarena"]

[tool.uv.sources]
textarena = { git = "https://github.com/jmilldotdev/TextArena.git" }
